### ISSUE TITLE
Atualizar esse repositorio e transformar ele na nossa nova upstream

### ISSUE THREAD

**Issue by dasprino007** [estacao-pirata/estacao-pirata#1]
Eu acho que gente devia substituir https://github.com/rbertoche/space-station-14 por esse repositório, porque o pirata tecnicamente esta virando seu próprio code e não somos mais uma downstream do wizden.

**Comment by rbertoche** [comment]
Já tá atualizado!
Ja coloquei os hooks também.
Tem que ver o que mais falta migrar

**Comment by rbertoche** [comment]
Criei repos separados pra Nuclear e RMC, mas o Nuclear ainda ta em branco. Pro do RMC eu fiz push hoje. Assim vai ficar mais organizado e a gente vai poder fazer uma limpa no excesso de branch.

**Comment by dasprino007** [comment]
Otimo
